# Generated by Django 2.2.10 on 2022-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220425_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='如果这里填写的价格为0,则表示当前课程购买的时候，没有永久有效的期限', max_digits=6, verbose_name='课程原价'),
        ),
    ]
