# Generated by Django 2.2.10 on 2022-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='iamge_url',
            field=models.ImageField(max_length=255, upload_to='banner', verbose_name='图片'),
        ),
    ]
