# Generated by Django 2.2.10 on 2022-04-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220415_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='iamge_url',
            new_name='image_url',
        ),
    ]
