# Generated by Django 2.2.10 on 2022-04-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220415_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='ling',
            new_name='link',
        ),
    ]
