# Generated by Django 2.2.10 on 2022-04-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220415_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='position',
            field=models.IntegerField(choices=[(1, '顶部导航'), (2, '脚部导航')], default=1, verbose_name='导航位置'),
        ),
    ]
