"""
Django settings for luffyapi project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#把apps目录下面所有的子应用设置为可以直接导包，那就需要把apps设置为默认导宝路径
import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-tz+^4fev^s1123lv6&7!w=+o!tudyp^^8k5y0uhd_capgyhn%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'api.luffycity.cn',
    'www.luffycity.cn'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',

    #跨域
    'corsheaders',
    'rest_framework',

    #Xadmin
    'xadmin',
    'crispy_forms',
    'reversion',

    #子应用
    'home',
    'users',
    'course',
    'cart',
    'order',
    'payments',

    'ckeditor',  # 富文本编辑器
    'ckeditor_uploader',  # 富文本编辑器上传图片模块
]

# CORS组的配置信息
CORS_ORIGIN_WHITELIST = (
    'http://www.luffycity.cn:8080',
)
CORS_ALLOW_CREDENTIALS = False  # 允许ajax跨域请求时携带cookie

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'luffyapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'luffyapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'luffy_user',
        'PASSWORD': 'luffy',
        'NAME': 'luffy',
    }
}


#短信token：3106d9d45fe948b8b558362606043c16
# 设置redis缓存
CACHES = {
    # 默认缓存
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # 项目上线时,需要调整这里的路径
        "LOCATION": "redis://127.0.0.1:6379/0",

        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # 提供给xadmin或者admin的session存储
    "session": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # 提供存储短信验证码
    "sms_code":{
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    # 提供存储购物车商品信息
    "cart": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/3",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
}

# 设置xadmin用户登录时,登录信息session保存到redis
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"


# 短信接口配置
SMS = {
    # 说明：主账号，登陆云通讯网站后，可在"控制台-应用"中看到开发者主账号ACCOUNT SID
    "_accountSid" : '8a216da8802d68fe0180358b8b5c0145',

    # 说明：主账号Token，登陆云通讯网站后，可在控制台-应用中看到开发者主账号AUTH TOKEN
    "_accountToken" : '3106d9d45fe948b8b558362606043c16',

    # 请使用管理控制台首页的APPID或自己创建应用的APPID
    "_appId" : '8a216da8802d68fe0180358b8cfd014c',

    # 说明：请求地址，生产环境配置成app.cloopen.com
    # 沙箱环境地址： sandboxapp.cloopen.com
    "_serverIP" : 'sandboxapp.cloopen.com',

    # 请求端口 ，生产环境为8883，沙箱环境也是这个
    "_serverPort":"8883",
    
    # REST API版本号
    "_softVersion": '2013-12-26',
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/ShangHai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# 访问静态文件的url地址前缀
STATIC_URL = '/static/'
# 设置django的静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,"static")
]

# 项目中存储上传文件的根目录[暂时配置]，注意，uploads目录需要手动创建否则上传文件时报错
MEDIA_ROOT=os.path.join(BASE_DIR,"uploads")
# 访问上传文件的url地址前缀
MEDIA_URL ="/media/"



#日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    #日志的格式
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {lineno:d} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    #日志的过滤信息
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    #日志的处理方式
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.path.dirname(BASE_DIR), 'logs/luffy.log'),
            'maxBytes': 300 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    #日志对象
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'propagate': True,
        },
    }
}

REST_FRAMEWORK = {
    #异常处理
    'EXCEPTION_HANDLER': 'luffyapi.utils.exceptions.custom_exception_handle',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

import datetime
JWT_AUTH = {
    #指明jwt有效时间
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=10),
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'users.utils.jwt_response_payload_handler',
}

#注册自定义用户模型,值的格式必须是：应用名.模型类名
AUTH_USER_MODEL= 'users.User'

#实现多条件判断登录
AUTHENTICATION_BACKENDS = [
    'users.utils.UsernameMobileAuthBackend',
]

# 富文本编辑器ckeditor配置
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # 工具条功能
        'height': 300,      # 编辑器高度
        # 'width': 300,     # 编辑器宽
    },
}
CKEDITOR_UPLOAD_PATH = ''  # 上传图片保存路径，留空则调用django的文件上传功能


# 支付宝配置信息
ALIAPY_CONFIG = {
    # "gateway_url": "https://openapi.alipay.com/gateway.do?", # 真实支付宝网关地址
    "gateway_url": "https://openapi.alipaydev.com/gateway.do?", # 沙箱支付宝网关地址
    "appid": "2021000119676831",
    "app_notify_url": None,
    # "app_private_key_path": os.path.join(BASE_DIR, "apps/payments/keys/app_private_key.pem"),
    "app_private_key_path": "-----BEGIN RSA PRIVATE KEY----- \n MIIEowIBAAKCAQEApaxiK5J6MhA7sihze0CQDWX53hFXmwh2PFjEXPRVEQj5vPWjauFMGYgD74S/iv/uCKFjDubQK0oZnvYDSZZ2gGywhIDzUT+JsLzPF4xcii2TCfZdnoXMnceAK46j0cXj7WkeG/ih6cv74IBPXBs9BGsNFDMrSzeRdRYQKmhI2ZDl0A07KflbmPcnCp2Ki2Yr9/hUcBIv6e7V5T2/qaU5ViK8OIV5GiJnEOLqeJ6bev0RZrBD7wOcfwDKRmWWRJim8fMJ0DuHklIMnLr583lusGdHP8Tv1uZUwoLRxAAKDag7y5MEEWUuCBCGDps05ZE2T/jiO3z806E+Db0bYqs+9wIDAQABAoIBABdBJhp1mf9S9f4g3WzMeCvZR4RbLM/PFUGNOCrQBOy6NMvIMuL6ssLWq67AFF6/Y7sEZDIgRdH9ubDtWTLIEuQd3X0L2Jtr7rjHF853XjnrAbuhQCzTHRB8g0oZ4Ha+byrQ2XAVqyx0/Grbt8f27s6i9BgEwqvxJdKogSZisu8OxMJjQoeBiPQ9imbiJwd1sVCDt/3Odod9F5pqN0rGqVM+ensocaguYXizOmxzrIYYO6/OhzmL9I5WkyDfYNkHyOtFpo7LPVHRodM5rE+CJE5ljO6hEgpAWl6aK7haRG98C0T8IDJtFwzm/mafzX+TqwtUG7JBCvLRTjXyacePPiECgYEA19fv4IXL1AvMDDtBcbb3gAYLtiN05wLkXotKzxx41KwJ+uxcm0WHovMn4K7F1gI8b7SQ6xBAya1dnJ1n9C6kHjj+6nehDTQoK10BqYgw21lX4+ey5c+R9lYT/rM/No04K/zOwI4LyUjKi9a423vlYD7iJxeTcvvUYbEPC0US8ccCgYEAxH75WHMHpCqAGtN2iX4reHu0jnMsQuuryf1d1uSrX+iF2lNz9GHrc8yPu5HaFHwnhZ13nsZZkinoYFoxQ5EU2FcI8X/K3qJuA/Sux6JJ//9uIxTkEx6q0Q2MZdl1BowVtRyfG1ce6UwkoTQfH+hC4BXX5GaZG09Dd7mVf1ltSVECgYAFNqsNok21Fn/cP8Yp6AB8cCjyQlL9jX1Up0qsTATDJlCrZfAqs/g9wF/TNoWC0NUC4bqqYt8dv/lF4itzo3jFXh0SLseOGRdrTLjQjoCXm8XatGsG0Ae3ioa7HTtGpwyXS2j3D7dLKl3yGMKoUorM01gFF7WxDlIn9e3mGMoHWwKBgAK2oijXhc59i8FTFDr31A/Y3XhuHLlb2cZzSj1ycO9lHZwTNPG1/HNf6sgzTmikAkO1FfbKVGhRTdUuyaleMoR+RzBWjG2gnpZNZbB6DD2NwG6ZlkCxVriGUF8DrrsFajNTDttoy5N7KrJTLu7Y3TuM8atEw25+HLdlh6v3hyvRAoGBALB3GpxK3LvV9GIZFryFi4NClGvAABcD4vbZ6xnd8WfHu5QhYzJYPeOnH0kA7MXsUjVUK1GxmakFASf2EzmtereL1FRtyABRP7xRz4PfuChHDZdqtHAKBSxAttriSJRhNH9jqUI1XBUq1087aFnFahaLdpP70pq8zz/RMWRLIfa+ \n -----END RSA PRIVATE KEY-----",
    # "alipay_public_key_path": os.path.join(BASE_DIR, "apps/payments/keys/aliapy_public_key.pem"),
    "alipay_public_key_path": "-----BEGIN PUBLIC KEY----- \n MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsZHsoaRqjEUcUOK5vw94v+RTfMHkUt0Z3Re31A0jR1jxpmaBcLV7im8FQTFVX04kFKc9qYTY2HQ8ouMEWYpkcsfdPId+GMH6BaZarK13BNlecvOhS8th6KOGjgHV2IiC48OkKMe1ojmPidhkYXCSUXptdGAkxfWaZi8q2m41DxjwH4IbYN1r/MTP1dwd4h+owoYmSjydpeV2JvL3AKuDYxAa3cXjYMxfeD5AgQ7j5OUwYeZ+S6bjjnyd3mtvQbQ3F09k/0TlqZFRiROdMIskUJKSpWPGnKucvwWqze8uDYSEMxCM0w0BYUbZuediz13nEcXGVShXDx9ircvbRFWX5QIDAQAB \n -----END PUBLIC KEY-----",
    "sign_type": "RSA2",
    "debug": True,
    "return_url": "http://www.luffycity.cn:8080/payments/result", # 同步回调地址
    "notify_url": "http://api.luffycity.cn:8000/payments/result", # 异步结果通知
}